import { expect, it } from 'vitest';
import { parseAcademicBackup } from '../src/utils/backup';
import { student, subjects, mappings, settings } from './fixtures';
it('restores the exact envelope generated by the download-backup button', () => {
  const backup = JSON.parse(JSON.stringify({ app: 'PPTQ Al-Husna Bukit Raja Wali - Raport', version: '1.0', data: { students: [student], subjects, classSubjects: mappings, teachers: [], settings, users: [], logs: [] } }));
  const result = parseAcademicBackup(backup);
  expect(result.students[0].id).toBe(student.id);
  expect(result.students[0].grades).toEqual(student.grades);
  expect(result.subjects).toEqual(subjects);
  expect(result.classSubjects).toEqual(mappings);
  expect(result.settings.semester).toBe('Genap');
});
it('rejects incomplete backups before any write starts', () => {
  expect(() => parseAcademicBackup({ data: { students: [] } })).toThrow('tidak lengkap');
});
